---
- name: configure main switch interface
  template:
    src: main.network.j2
    dest: /etc/systemd/network/switch.network

- name: install vlan interfaces
  template:
    src: vlan.netdev.j2
    dest: "/etc/systemd/network/switch.{{ item }}.netdev"
  loop: "{{ range(2, switch_no+2)|list }}"

- name: configure vlan interfaces
  template:
    src: vlan.network.j2
    dest: "/etc/systemd/network/switch.{{ item }}.network"
  loop: "{{ range(2, switch_no+2)|list }}"