---
- name: configure main switch interface
  template:
    src: main.network.j2
    dest: "/etc/systemd/network/{{ switch_interface }}.network"

- name: install vlan interfaces
  template:
    src: vlan.netdev.j2
    dest: "/etc/systemd/network/port-{{ item }}.netdev"
  loop: "{{switch_vlans}}"

- name: configure vlan interfaces
  template:
    src: vlan.network.j2
    dest: "/etc/systemd/network/port-{{ item }}.network"
  loop: "{{switch_vlans}}"