all:
  children:
    routers:
      hosts:
        worldrouter:
          ansible_user: root 
          ansible_ssh_common_args: -F ssh_config 
          ansible_python_interpreter: /usr/bin/python3
          switch_interface: eth0 # The physical interface connected to vlan capable switch
          switch_vlans: "{{ range(1, 49)|list }}"
